sprint-1/step-2
BogdanovSergey/react-burger pull request #5
Opened 2021-08-10 07:16 UTC by BogdanovSergey

2021-08-10 09:17 UTC, SmilingJey requested changes
Здравствуйте!

Хорошая работа, проект почти полность соответвует макету, реализовано открытие попапов через портал, но есть несколько замесечаний в реализации функционала:

**Основные места, которые нужно исправить:**

- добавьте проверку, ответа сервера - res.ok при запросе

- передавайте нужное содержимое попапа как children, а не через type

- размер попапа сильно меньше, чем должен быть по макету

- задний фон (оверлей) у открытого попапа должен быть не светлый как сейчас, а  темный

- не нужно хардкодить названия категорий в ProductListProps , передавайте название категории как пропс в компонент

**Более мелкие замечания и места, в которых можно улучшить проект так же отмечены в коде:**

2021-08-10 09:17 UTC, SmilingJey commented on src/components/portal/portal.jsx
> +					<span className="text text_type_main-medium" style={{paddingLeft:'20px',position:'relative',float:'left'}}>{props.type==='product' && 'Детали ингредиента'}</span>
**Надо исправить**

Не используйте type, сделайте пропс с текстом заголовка и отображайте его, если он передан

2021-08-10 09:17 UTC, SmilingJey commented on src/components/portal/portal.jsx
> +		        {props.type==='order' && <OrderDetails/>}
**Надо исправить**

Не используйте type, передавайте нужный контент попапа как children

2021-08-10 09:17 UTC, SmilingJey commented on src/components/portal/portal.jsx
> +
**Надо исправить**

задний фон  (оверлей) у открытого попапа должен быть не светлый как сейчас 

![2021-08-10_12-04-30](https://user-images.githubusercontent.com/9317133/128839623-1f579d46-36c1-4a7f-9b48-82700667295d.png)

А темный

![2021-08-10_12-05-29](https://user-images.githubusercontent.com/9317133/128839769-7acceff7-637c-4db0-addd-7ca7aa994a1d.png)

2021-08-10 09:17 UTC, SmilingJey commented on src/components/portal/order-details.jsx
> +export const OrderDetails = () => {
**Надо исправить**

Размер попапа сильно меньше

![2021-08-10_12-07-30](https://user-images.githubusercontent.com/9317133/128840287-326dd1a8-2cda-4520-bc12-c89e73eeeb13.png)


 чем должен быть по макету

![2021-08-10_12-08-16](https://user-images.githubusercontent.com/9317133/128840315-66708785-330a-4ddc-948e-9c96beae4a4f.png)

Увеличьте размер шрифта

2021-08-10 09:17 UTC, SmilingJey commented on src/components/portal/ingredient-details.jsx
> +export const IngredientDetails = (props) => {
**Надо исправить**

Размер попапа сильно меньше

![2021-08-10_12-04-30](https://user-images.githubusercontent.com/9317133/128840405-28d7c197-0bd2-47e9-a244-95d54f463c75.png)



 чем должен быть по макету

![2021-08-10_12-05-29](https://user-images.githubusercontent.com/9317133/128840417-4fa67f18-5a3b-4c36-bf23-c078d01f05fd.png)


Увеличьте размер шрифта

2021-08-15 17:34 UTC, SmilingJey requested changes
Вы хорошо поработали над проектом, но несколько замечаний, которые нужно исправить, остались:

- опишите propTypes у компонентов, это требуется по заданию

Лучше вынести в файл prop-types.js описание пропсов ингредиента

```
export const ingredientPropTypes = PropTypes.shape({
  ............
}).isRequired
```
и переиспользовать это описание

- поправьте стили ссылок в шапке и ингредиентов, т.к. их отображение сейчас сильно отличается от макета

Отметил так же несколько мест "Можно лучше" - старайтесь не использовть инлайновые стили и обратите внимание на замечание в norma-api

2021-08-15 17:34 UTC, SmilingJey commented on src/utils/norma-api.jsx
> +export const getApiData = function(apiUrl, setApiData) {
**Можно лучше**

используйте не передачу колбэка, а возврат промиса

```
export const getApiData = function(apiUrl) {
    fetch(apiUrl)
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                throw new Error("Can't get data from Api");
            }
        })
}
```

```
    useEffect(()=>{
        getApiData(apiUrl)
        .then(result => {
            setApiData(result.data);
        })
        .catch(error => {
            console.log(error);
            alert('Error connecting to Api');
        });
    },[apiUrl, setApiData]);
```

2021-08-15 17:34 UTC, SmilingJey commented on src/components/app-header/app-header.jsx
> +	                <a href="#" className={css.inmenu}>
**Надо исправить**

задайте ссылке стили, что бы цвет текста соответствовал макету

Как выглядит сейчас:
![2021-08-15_20-10-32](https://user-images.githubusercontent.com/9317133/129486655-154fd4b9-c1bf-4de6-bf11-8614fb7f6fb3.png)


Макет:

![2021-08-15_20-12-32](https://user-images.githubusercontent.com/9317133/129486661-b6ed579b-5907-4139-90df-eeba7c951e05.png)

2021-08-15 17:34 UTC, SmilingJey commented on src/components/portal/ingredient-details.jsx
> +	productData : PropTypes.any
**Надо исправить**

Нужно дать более детальное описание proptypes

2021-08-15 17:34 UTC, SmilingJey commented on src/components/burger-ingredients/burger-ingredients.jsx
> +export const BurgerIngredients = (props) => {
**Надо исправить**

опишите propTypes компонента

Т.к. во многих компонентах дублируется описание PropTypes ингредиента лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src ) и переиспользовать описание пропсов ингрединта

2021-08-15 17:34 UTC, SmilingJey commented on src/components/portal/order-details.jsx
> +			<p className="text text_type_main-medium" style={{padding:'15px',paddingBottom:'40px'}}>идентификатор заказа</p>
**Можно лучше**

не используйте инлайновые стили, вынесите в css файл

2021-08-15 17:34 UTC, SmilingJey commented on src/components/portal/portal.jsx
> +	const header = (typeof(chArr[0]) === 'string') ? chArr[0] : null;
**Можно лучше**

лучше передавать текст заголовка просто пропсом

2021-08-15 17:34 UTC, SmilingJey commented on src/components/product/product.jsx
> +            <span style={{display: 'inline-flex'}}>
**Надо исправить**

используйте типографику из библиотеки и задайте выравнивание по центру, что бы отображение ингредиента соответствовало макету

Сейчас:
![2021-08-15_20-23-27](https://user-images.githubusercontent.com/9317133/129486987-ce81a356-967d-4535-a915-190a191c0442.png)


Макет:

![2021-08-15_20-23-45](https://user-images.githubusercontent.com/9317133/129486992-fd7cce9a-d2e5-4e2a-8515-3b8dbc608005.png)

2021-08-15 17:34 UTC, SmilingJey commented on src/components/product/product.jsx
> +export const Product = ({apiData}) => {
**Надо исправить**

опишите propTypes у компонента

2021-08-15 17:34 UTC, SmilingJey commented on src/components/product-list/product-list.jsx
> +export const ProductList = (props) => {
**Надо исправить**

опишите propTypes у компонента

2021-08-17 11:13 UTC, SmilingJey approved these changes
Отлично, замечания исправлены, теперь проект соответствует макету и описаны PropTypes, но не забудьте поправить отмеченное замечание - в этот файл нужно было вынести только описание PropTypes, которые повторяются - только ингредиента. Перенесите описание проптайпс остальных компонентов в их файлы, не нужно выносить в общий файл

Успехов в дальнейшем обучении!

2021-08-17 11:13 UTC, SmilingJey commented on src/prop-types.js
> +export const ingredientPropType = {
**Надо исправить**

в этот файл нужно было вынести только описание PropTypes, которые повторяются - только ингредиента. Перенесите описание проптайпс остальных компонентов в их файлы, не нужно выносить в общий файл

2021-08-17 12:13 UTC, BogdanovSergey commented on src/prop-types.js
> +export const ingredientPropType = {
Спасибо, исправил!

2022-04-19 03:44 UTC, closed without merging